198 cms show language of unsaved changes
bccsa/luminary pull request #228
Opened 2024-07-15 12:03 UTC by belljohan3

- Add in validation area.
 - Unsaved changes to the Post / Tag (parent) document to show in General
 - Unsaved changes to ContentDto's (child documents) to show per ContentDto language
 - Rename "Validation errors" to "Validation"
 - Remove current "Unsaved Changes" label.
 - Use a yellow "info" icon for unsaved changes

2024-07-15 19:26 UTC, ivanslabbert requested changes
@belljohan3 
When there are no validation errors, the unsaved changes does not show:
![image](https://github.com/user-attachments/assets/67860489-415f-4374-91ac-e272a3bee3e3)

Would it look better if the unsaved changes looks the same as validation errors, but with a yellow "info" icon?
![image](https://github.com/user-attachments/assets/95b9564f-c8d5-460c-b11b-cd103ee7130a)

2024-07-15 19:28 UTC, ivanslabbert commented
Would also be nice to have some tests to check that the unsaved changes validation is showing as expected.

2024-07-16 09:20 UTC, belljohan3 commented
![image](https://github.com/user-attachments/assets/688fda9b-2594-4db9-ab6e-118e797c8085)

This is what i did on validations

2024-07-19 13:38 UTC, ivanslabbert requested changes
When making a change that triggers a validation error, the "unsaved changes" message also appears under the General section
![image](https://github.com/user-attachments/assets/4eec7a22-6b12-427b-9de4-bce6c7bb81f1)

2024-07-23 12:52 UTC, ivanslabbert requested changes
Hi @belljohan3 
Can you move this text to be next to the save button?
![telegram-cloud-photo-size-4-5836830808776753206-x](https://github.com/user-attachments/assets/70e3e2c5-48fb-48f6-8ce2-02c4a230e706)

2024-07-23 12:57 UTC, ivanslabbert commented on cms/src/components/content/EditContentParentValidation.vue
>                          :languages="props.languages"
Add a sort function to languages prop like something like this?
`:languages="languages.sort(sortByName)"`

It is also not necessary to write "props.xxx" in the template section.

2024-07-23 12:57 UTC, ivanslabbert commented on cms/src/components/content/EditContentParentValidation.vue
> +                        :contentPrev="props.contentPrev?.find((c) => c._id == content._id)"
Not needed to write `props.xxx`?

2024-07-23 16:53 UTC, belljohan3 commented
Hey @ivanslabbert ! 
There is something that we should have a look at. 
Actually, the languages are sorted on EditContent for categories but not in the post. I tried what you said but it didn't work. 

I think we need to look a bit at it. Normally it should work everywhere as it is a Generic component.

2024-07-26 18:36 UTC, ivanslabbert requested changes
I did a quick check, and it looks nice.
![image](https://github.com/user-attachments/assets/e189d6e3-2e6e-4fab-97cc-fd2540fa73bc)

But when clicking on the badges next to the language labels, it routes with an incorrect router link (it appends the language code to the content document ID in the URL)
![telegram-cloud-photo-size-4-5845722061094372585-x](https://github.com/user-attachments/assets/ed4fc2e8-baa4-4c25-bb11-6be036d7e4ce)

Perhaps have a look on how the language switching was done in the language switcher?

2024-07-29 07:18 UTC, ivanslabbert approved these changes
Please just fix this? https://github.com/bccsa/luminary/pull/228/files#r1688018433

2024-07-29 09:25 UTC, merged