Refactor group editor
bccsa/luminary pull request #230
Opened 2024-07-17 22:04 UTC by ivanslabbert

2024-07-19 13:06 UTC, laurensgroeneveld requested changes
Just found some small issues, nothing major.

2024-07-19 13:06 UTC, laurensgroeneveld commented on cms/src/components/groups/EditGroup.vue
> +const original_cleaned = ref<GroupDto>(props.group);
Also, took me a bit to understand the naming here. I suggest naming it something a little more descriptive like `originalGroupWithoutEmpty`. Or, if you really want to stick to a shorter name, have more descriptive comments here and for the watchers.

2024-07-19 13:30 UTC, ivanslabbert commented on cms/src/components/groups/EditAclByGroup.vue
> +import _ from "lodash";
I only installed "lodash.clonedeep" and "lodash.isequal", so I would think it is not that heavy then?
![image](https://github.com/user-attachments/assets/b11f294c-84dd-4111-85e6-49f46b605aef)

2024-07-19 13:32 UTC, ivanslabbert commented on cms/src/components/groups/DuplicateGroupAclButton.vue
Think the issue was there before as well - I did not (at least knowingly) make changes to CSS.

2024-07-20 08:16 UTC, ivanslabbert commented on cms/src/components/groups/DuplicateGroupAclButton.vue
Suddenly showed correctly in my Chrome browser without making the change. But I changed the Menubutton element to be selfclosing, so please check if it renders correctly?

2024-07-20 08:21 UTC, ivanslabbert commented on cms/src/components/groups/DuplicateGroupAclButton.vue
Changed the popup to right-align, so that it will not expand the parent element.

2024-07-20 08:53 UTC, ivanslabbert commented on cms/src/components/groups/AddGroupAclButton.vue
It is actually a valid selection. In this way you can give users who are members of a giving group direct access to documents who are also members of the same group. (We are using it on the Super Admins group.)

The usual way is however to make a group for users and another group for documents.

2024-07-20 09:23 UTC, ivanslabbert commented on cms/src/components/groups/DuplicateGroupAclButton.vue
Found the issue - EditAclByGroup.vue had an "overflow-x-auto" set.

2024-07-22 14:52 UTC, ivanslabbert commented on cms/src/components/groups/EditAclByGroup.vue
> +import _ from "lodash";
As far as I can read Lodash is newer than Underscore, and it has more frequent updates and is used more widely.

2024-07-23 09:57 UTC, laurensgroeneveld commented on cms/src/components/groups/EditAclByGroup.vue
> +import _ from "lodash";
> As far as I can read Lodash is newer than Underscore, and it has more frequent updates and is used more widely.

Ah then I probably mixed them up 😅. I still think we should rather reach for native JS solutions wherever possible, to reduce our amount of dependencies. But it's also fine to keep it like this.

2024-07-23 10:00 UTC, laurensgroeneveld commented on cms/src/components/groups/DuplicateGroupAclButton.vue
Hmm I still see this, I can also see it renders an empty `span` inside the button which means Vue rendered the (empty) slot. This is about the duplicate button on the group ACL, not the group itself:

<img width="898" alt="image" src="https://github.com/user-attachments/assets/20d64539-0bf8-4f80-8b00-21352c1f20a9">

2024-07-23 10:01 UTC, laurensgroeneveld approved these changes
Just added two additional comments but otherwise looks good 👍

2024-07-23 12:08 UTC, merged