add link dates toggle
bccsa/luminary pull request #280
Opened 2024-08-06 13:55 UTC by DirkDevelopmentFreelance

add link dates toggle and add "linkDates" as an optional field for PostDTo.  Discuss API tests that fail?

2024-08-07 07:57 UTC, ivanslabbert requested changes

2024-08-07 07:57 UTC, ivanslabbert commented on api/src/dto/PostDto.ts
> +    linkDates: boolean;
```suggestion
@IsOptional()
    linkDates?: boolean;
```

2024-08-10 15:24 UTC, laurensgroeneveld reviewed
I just have two small comments, but also a more general question. This code looks fine, but I don't have a good insight in what problem is solved here. I'm guessing it will link publish date & expiry date across translations?

On its own, this will not do anything, which in general I'm not a huge fan of: in other places we've removed UI elements for features that we plan to do but are not there yet, as it can lead to confusion.

I'm also wondering whether just a "link dates" toggle is clear enough for less technical users. Should there be some visual indication on the dates that they are linked? Should the toggle be on by default? Note that we're also touching the date fields in #246 so it might not be a good idea to do that in this particular PR.

2024-08-10 15:24 UTC, laurensgroeneveld commented on cms/src/components/content/EditContentParent.spec.ts
> +        // // Check if the LToggle component is rendered
Nitpick: I see you copied the comment from above, but in my opinion it's superfluous and we can do without it as the code makes it clear enough what's happening.

2024-08-10 15:24 UTC, laurensgroeneveld commented on cms/src/components/content/EditContentParent.spec.ts
> +    it("test the link date toggle", async () => {
I see the other tests in this file have similar names, but I think they can be written a bit more clearly. Generally I would recommend writing it in a sentence form (it already starts with "it", so write whatever comes after that: "it does X when I click Y" for example). And when this test fails, a clear description of what this test does helps to view at a glance what might be wrong. My suggestion for this specific case would be something like "it renders the link dates toggle with the correct initial state". 

Do you agree that makes it clearer? In that case I suggest to also rewrite the other test names in this file.

On a separate note, we could perhaps add a test or assertion in this same test that we can toggle it, and that it updates the right value on the parent.

2024-08-12 07:59 UTC, ivanslabbert commented
After discussion on 2024/08/12, we decided that there are complications around a linked-date functionality, especially w.r.t. translation permissions (should a user be able to change the dates of content to which he does not have translate permissions).

We are putting this on ice for now.

2024-08-12 07:59 UTC, closed without merging