option to hide the publish date
bccsa/luminary pull request #302
Opened 2024-08-24 17:32 UTC by belljohan3

2024-08-26 03:43 UTC, ivanslabbert requested changes
Good work @belljohan3 

Some comments:

- The field must also be added to ContentDto, and copied from the incoming PostDto/TagDto in the API
- I think we need to add something to set the default value of `publishDateVisible` to false when creating a new Tag. On Posts the default of true is good. Should be ok to only do this in the CMS.
- Add a test to check if the publish date is shown when `publishDateVisible` is `undefined` (if you have not done so already)
- Add a Add a test to check if the publish date is hidden when `publishDateVisible` is `false` (if you have not done so already)

2024-08-26 08:51 UTC, belljohan3 commented
As discussed, it might be better to run an upgrade in the database schema with functionnality added to #290.

2024-08-26 15:05 UTC, ivanslabbert commented
@belljohan3 we should please go through the conflicts together to avoid reverting recent changes that was merged to main?

2024-08-27 10:55 UTC, ivanslabbert commented
@belljohan3 I am getting an error in the CMS console when loading an existing Post / Tag document:
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/0b77640c-c205-4a26-bb17-3a45c8304bca">

2024-08-27 11:08 UTC, belljohan3 commented
Yes I am aware of that. It is coming from EditContentParent component. It seems like we need a computed function that set a the new value to the publishdateVisible when the parent changed

2024-08-27 11:10 UTC, ivanslabbert requested changes
As an upgrade script has been added updating existing documents to include `publishDateVisible` field, we can remove code in the CMS and app handling cases where `publishDateVisible` is undefined. The field can also be made mandatory (currently it is optional).

2024-08-27 11:10 UTC, ivanslabbert commented on cms/src/components/content/EditContent.vue
> +        publishDateVisible: true,
No need to set the `publishDateVisible` field on the ContentDto documents as this is done in the API.

2024-08-27 11:10 UTC, ivanslabbert commented on cms/src/components/content/EditContentParentValidation.vue
> +        publishDateVisible: true,
No need to set the `publishDateVisible` field on the `ContentDto` documents as this is done in the API.

2024-08-27 11:10 UTC, ivanslabbert commented on cms/src/tests/mockdata.ts
> +    publishDateVisible: true,
```suggestion
    publishDateVisible: false,
```

2024-08-27 11:10 UTC, ivanslabbert commented on cms/src/tests/mockdata.ts
> +    publishDateVisible: true,
```suggestion
    publishDateVisible: false,
```

2024-08-27 11:10 UTC, ivanslabbert commented on cms/src/tests/mockdata.ts
> +    publishDateVisible: true,
```suggestion
    publishDateVisible: false,
```

2024-08-27 11:10 UTC, ivanslabbert commented on cms/src/tests/mockdata.ts
> +    publishDateVisible: true,
```suggestion
    publishDateVisible: false,
```

2024-08-27 11:10 UTC, ivanslabbert commented on api/src/dto/ContentDto.ts
> +    publishDateVisible?: boolean;
This is perhaps debatable, but as this field is replicated from the parent post/tag document, it should perhaps be renamed to `parentPublishDateVisible` to keep it in line with other replicated fields?

2024-08-28 06:45 UTC, ivanslabbert commented
> Yes I am aware of that. It is coming from EditContentParent component. It seems like we need a computed function that set a the new value to the publishdateVisible when the parent changed

Or use a v-if on the toggle component?

2024-08-28 07:44 UTC, belljohan3 commented
> > Yes I am aware of that. It is coming from EditContentParent component. It seems like we need a computed function that set a the new value to the publishdateVisible when the parent changed
> 
> Or use a v-if on the toggle component?

I think as the field is now mandatory, the warning is not showing anymore.

2024-08-28 08:44 UTC, ivanslabbert approved these changes
Approved, but please have a look at two minor things I commented on?

2024-08-28 08:44 UTC, ivanslabbert commented on app/src/components/content/ContentTile.spec.ts
> +    it("hides the publishDate is false", async () => {
```suggestion
    it("hides the publishDate of publishDateVisible is false", async () => {
```

2024-08-28 08:44 UTC, ivanslabbert commented on app/src/components/content/ContentTile.vue
> +            v-if="props.showPublishDate && content.parentPublishDateVisible"
Not needed to include `props.xxx` in the html as Vue does this automatically

2024-08-28 08:53 UTC, merged