Add redirect document type
bccsa/luminary pull request #429
Opened 2024-10-17 11:02 UTC by DirkDevelopmentFreelance

2024-10-22 07:42 UTC, ivanslabbert requested changes

2024-10-22 07:42 UTC, ivanslabbert commented on api/src/dto/RedirectDto.ts
> +    toSlug: string;
Add a '?' to show toSlug is optional

2024-10-22 07:42 UTC, ivanslabbert commented on api/src/dto/RedirectDto.ts
> +    toUrl: string;
add a '?' to show toUrl is optional

2024-10-22 09:28 UTC, DirkDevelopmentFreelance commented on api/src/dto/RedirectDto.ts
> +    toSlug: string;
Added

2024-10-30 09:42 UTC, closed without merging

2024-10-30 09:42 UTC, DirkDevelopmentFreelance commented
Conflicting changes that is too far gone to save so remade this PR.