CMS: Add testable combobox component
bccsa/luminary pull request #451
Opened 2024-10-23 06:35 UTC by DirkDevelopmentFreelance

2024-10-24 07:14 UTC, ivanslabbert requested changes
Blocking merging until reviewed by Johan and checked by Ivan

2024-10-25 09:18 UTC, belljohan3 commented on cms/src/components/forms/LCombobox.vue
> +        <FormLabel> Group Membership </FormLabel>
```suggestion
        <FormLabel> Group membership </FormLabel>
```

2024-10-25 09:28 UTC, belljohan3 requested changes
It works well but we need to do more on UX.

- When clicking on a group in the list, the dropdown list is still showing
- When searching for a group in the input, the dropdown is in full height. 
![image](https://github.com/user-attachments/assets/33ce9f73-745a-4060-98d5-c6aff88a0b94)

2024-10-28 08:48 UTC, belljohan3 approved these changes
Nice job

2024-11-02 09:16 UTC, ivanslabbert requested changes
Hi Dirk

This looks good, but...
The Combobox is now specific for showing groups and not a generic component that we can use for any combobox implementation. We will now have to copy this code and modify it for tag selectors and any other selectors we need.

Would it be possible to make it a generic combobox (a bit like HeadlessUI have done) that we can use for different combobox use cases?

2024-11-15 09:54 UTC, ivanslabbert commented on cms/src/components/content/EditContentParent.vue
> +import LCombobox from "../forms/LCombobox.vue";
Linting error

2024-11-15 09:54 UTC, ivanslabbert commented on cms/src/components/forms/LCombobox.spec.ts
> +        { timeout: 100000 },
This is a very long timeout? Guess it was used during debugging?

2024-11-15 09:54 UTC, ivanslabbert commented on cms/src/components/forms/LCombobox.vue
> +//const selected = ref<Array<string | number>>([])
remove commented code?

2024-11-15 09:54 UTC, ivanslabbert commented on cms/src/components/forms/LCombobox.vue
> +const optionsDisplay = ref();
The naming is a bit confusing (as we also have an `optionsToDisplay`). Perhaps something like `optionsElement` or `optionsDiv` could work?

2024-11-15 09:54 UTC, ivanslabbert commented on cms/src/components/forms/LCombobox.vue
> +                                console.log(selectedOptions);
remove console.log

2024-11-15 09:54 UTC, ivanslabbert commented on cms/src/components/forms/LCombobox.vue
> +const optionsToDisplay = ref(optionsList.value);
Not sure why we need this? A computed is already a ref.

2024-11-15 09:54 UTC, ivanslabbert commented on cms/src/components/forms/LCombobox.vue
> +                    :disabled="selectedOptions?.includes(option.id)"
You should already have a `selected` parameter in `optionsToDisplay` which removes the need to recalculate it here?
```suggestion
                    :disabled="option.selected"
```

2024-11-15 09:54 UTC, ivanslabbert commented on cms/src/components/forms/LCombobox.vue
> +                            ),
```suggestion
                            'bg-white text-black hover:bg-zinc-100': !option.selected,
```

2024-11-15 09:54 UTC, ivanslabbert commented on cms/src/components/forms/LCombobox.vue
> +                            'text-zinc-500 hover:bg-white': selectedOptions?.includes(option.id),
```suggestion
                            'text-zinc-500 hover:bg-white': option.selected,
```

2024-11-15 09:54 UTC, ivanslabbert commented on cms/src/components/forms/LCombobox.vue
> +                            if (!selectedOptions?.includes(option.id)) {
```suggestion
                            if (!option.selected) {
```

2024-11-15 09:54 UTC, ivanslabbert commented on cms/src/components/languages/CreateOrEditLanguageModal.vue
> +const selected = ref([]);
Guess you would still do some cleanup here...

2024-11-18 09:21 UTC, ivanslabbert approved these changes

2024-11-18 09:22 UTC, merged