add seoTitle and seoSummary as meta data
bccsa/luminary pull request #456
Opened 2024-10-23 18:59 UTC by belljohan3

2024-10-24 07:21 UTC, ivanslabbert requested changes
Blocking merging until reviewed

2024-10-24 07:56 UTC, DirkDevelopmentFreelance reviewed
The code looks nice and clean, nice research done. @ivanslabbert, just double check the functionality as I am not entirely sure how to find the metadata inside the browser, tried an extension but it doesn't work on local sites. Nice Work @belljohan3

2024-10-24 08:29 UTC, belljohan3 commented
> The code looks nice and clean, nice research done. @ivanslabbert, just double check the functionality as I am not entirely sure how to find the metadata inside the browser, tried an extension but it doesn't work on local sites. Nice Work @belljohan3

You can inspect the current doc and check the meta data in the `head` tag.

2024-10-24 20:12 UTC, ivanslabbert requested changes

2024-10-24 20:12 UTC, ivanslabbert commented on app/src/pages/SingleContent.vue
> +import { useHead } from "@vueuse/head";
According to the plugin's GitHub page, it has been replaced with Unhead/vue, so the best will be to use the new package.

But to keep our application as lightweight as possible, I would suggest not using a plugin to set the title and metadata, but rather set the title as currently done in line 44, and setting the metadata as per https://stackoverflow.com/questions/2568760/is-it-possible-to-use-javascript-to-change-the-meta-tags-of-the-page

2024-10-24 20:12 UTC, ivanslabbert commented on app/src/pages/SingleContent.vue
> +                name: "summary",
```suggestion
                name: "description",
```
the "summary" metadata tag is not supported by Google's indexer

2024-10-24 20:12 UTC, ivanslabbert commented on app/src/pages/SingleContent.vue
> +        : `${content.value.title} - ${appName}`;
We are now setting the title in two locations in the code, both direcetly using the "document" api as well as through the useHead plugin. We should combine the logic.

2024-10-25 08:04 UTC, belljohan3 commented
@ivanslabbert  Here is also a nice way to set it. 

`[
    { name: "title", content: content.value.seoTitle || content.value.title || "" },
    { name: "description", content: content.value.seoString || content.value.summary || "" },
].forEach(attrs => {
    const metaTag = Object.assign(document.createElement("meta"), attrs);
    document.head.appendChild(metaTag);
});`

2024-10-25 13:03 UTC, ivanslabbert requested changes
Added 1 change request.

Can we also add a test to see if the title is being set correctly at the <head> title tag, and if the "description" metadata is set correctly?

2024-10-25 13:03 UTC, ivanslabbert commented on app/src/pages/SingleContent.vue
> +        { name: "title", content: content.value.seoTitle || content.value.title || "" },
Google does not support the "title" metadata (see https://developers.google.com/search/docs/crawling-indexing/special-tags). We could rather set the document.title to the SEO title if available (in line 43)

Your implementation for the description metadata tag looks good.

2024-10-28 20:25 UTC, ivanslabbert approved these changes

2024-10-29 12:56 UTC, merged