Remove domain specific references
bccsa/luminary pull request #457
Opened 2024-10-24 09:39 UTC by DirkDevelopmentFreelance

2024-10-24 09:40 UTC, DirkDevelopmentFreelance commented
Should I remove all domain specific references inside tailwind css and classes?

2024-10-25 07:30 UTC, ivanslabbert requested changes

2024-10-25 07:30 UTC, ivanslabbert commented on api/.env.example
> +ORIGIN=[
```suggestion
CORS_ORIGIN=[
```

2024-10-25 07:30 UTC, ivanslabbert commented on api/src/main.ts
> +        origin: process.env.ORIGIN,
```suggestion
        origin: process.env.CORS_ORIGIN,
```

2024-10-25 07:30 UTC, ivanslabbert commented on app/.env.example
> +VITE_LOGO_SVG='<svg></svg>'
Change to VITE_LOGO and VITE_LOGO_SMALL. Add comments in the example env file to explain the different uses. The variable value should be the relative path or absolute http link to the file.

2024-10-25 07:30 UTC, ivanslabbert commented on app/src/components/LLogo.vue
> +</template>
This component can be removed and logo implemented directly in TopBar.vue

2024-10-25 07:30 UTC, ivanslabbert commented on app/src/components/navigation/TopBar.vue
> +const BRAND_NAME = import.meta.env.VITE_BRAND_NAME;
Rather use logos instead of text based brand name

2024-10-25 07:30 UTC, ivanslabbert commented on app/src/pages/LoginPage.vue
> +import LLogo from "@/components/LLogo.vue";
Do not change this yet (keep the original BCC logo). This will be updated when the Auth0 integration is redone

2024-10-30 13:50 UTC, merged