changed vite to load plugins from a configurable folder location
bccsa/luminary pull request #479
Opened 2024-10-31 12:51 UTC by oslabbie

2024-11-02 09:39 UTC, ivanslabbert requested changes
Can you explain a bit how plugins can access the vue app? I see it is exported now, so I guess it will be through that export?

2024-11-02 09:39 UTC, ivanslabbert commented on app/README.md
> +-   Set the VITE_PLUGIN_PATH env variable in your .env, then vite will go fetch your files at that location and copy it into the [plugins folder](./src/plugins/)
```suggestion
-   Set the `VITE_PLUGIN_PATH` env variable in your .env for vite to copy your plugins to the [plugins folder](./src/plugins/)
```

2024-11-02 09:39 UTC, ivanslabbert commented on app/README.md
>  -   To let luminary run the plugin you need to add a env variable VITE_PLUGINS to your env file and add an array of the plugins you want to add
```suggestion
-   To let luminary run the plugin you need to add an env variable `VITE_PLUGINS` to your env file with an array of plugin names.
```

2024-11-02 09:39 UTC, ivanslabbert commented on app/README.md
> +**The files is being copied everytime before vite build, dev, and test is run**
```suggestion
**The files are copied before vite build, dev, and test runs**
```

2024-11-02 09:39 UTC, ivanslabbert commented on app/README.md
>  #### How to add plugins
```suggestion
#### Adding plugins
```

2024-11-04 07:10 UTC, oslabbie commented
Hey @ivanslabbert 

Yes it is through the export, 
If you know of a better way, welcome to suggest it, then i can impliment it

2024-11-04 08:02 UTC, ivanslabbert approved these changes

2024-11-04 08:05 UTC, merged