display one banner notification at a time
bccsa/luminary pull request #556
Opened 2024-11-26 12:28 UTC by belljohan3

2024-11-27 09:52 UTC, DirkDevelopmentFreelance requested changes
I don't see the "You are offline" banner anymore after accepting the Notification banner anymore.

2024-11-27 11:07 UTC, ivanslabbert commented
I think we need to do a little more here. When one notification is dismissed (either by the user or programmatically), the next notification in the queue should pop up after say 3 seconds.

2024-12-03 07:23 UTC, DirkDevelopmentFreelance reviewed
Looks like it's working to me

2024-12-04 07:12 UTC, ivanslabbert requested changes
We need a pause of 2 seconds before displaying the next queued banner notification.

2024-12-04 07:12 UTC, ivanslabbert commented on app/src/App.vue
> +}, 1000);
Can we make this longer?

2024-12-10 12:54 UTC, belljohan3 commented
When we make the notification longer the tests fails for some of the reason.

2025-01-09 11:48 UTC, ivanslabbert approved these changes

2025-01-09 11:56 UTC, merged