add theme toogle icon
bccsa/luminary pull request #561
Opened 2024-11-29 08:06 UTC by belljohan3

2025-01-24 06:05 UTC, DirkDevelopmentFreelance submitted a review, later dismissed

2025-01-24 06:05 UTC, DirkDevelopmentFreelance commented on app/src/components/navigation/ThemeSelectorModal.vue
>  import LButton from "../button/LButton.vue";
The theme selector just has to be updated to sync with useDark, see ``TopBar.vue``

2025-01-24 06:05 UTC, DirkDevelopmentFreelance commented on app/src/components/navigation/ThemeSelectorModal.vue
> +import { SunIcon, MoonIcon, AdjustmentsHorizontalIcon } from "@heroicons/vue/24/outline";
Remove unused import

2025-01-24 06:05 UTC, DirkDevelopmentFreelance commented on app/src/components/navigation/TopBar.vue
> +const isDarkMode = useDark();
I added this, useDark works with user preference when loading up the website for the first time

2025-01-24 06:05 UTC, DirkDevelopmentFreelance commented on app/src/components/navigation/TopBar.vue
> +                    <div @click="isDarkMode = !isDarkMode" class="hidden items-center lg:flex">
Replaced the component element with a normal div as a component here wasn't necessary

2025-01-24 07:33 UTC, belljohan3 commented
Thanks @DirkDevelopmentFreelance . But don't you think taht it should open the modal first ? @ivanslabbert what is your take on this ? According to me, toogling directly on the icon should be fine.

2025-01-24 07:46 UTC, DirkDevelopmentFreelance commented
> Thanks @DirkDevelopmentFreelance . But don't you think taht it should open the modal first ? @ivanslabbert what is your take on this ? According to me, toogling directly on the icon should be fine. 
> 

You can do what you feel will work, I don't have a specific idea for the implementation for the toggle, just wanted to give you an example to work with😇

2025-01-28 11:09 UTC, ivanslabbert requested changes
- [ ] When changing the theme from the theme selector modal, the theme is not saved and reverts back to the old theme after reload. The modal however saves it's state, so it seems as if we are saving the state in two places now.
- [ ] Theme selector shortcut button is only showing in desktop mode, not in mobile.
- [ ] Theme selector shortcut button is too emphasized (should be less black / less white)
- [ ] Feels like the theme selector button is a bit too close to the profile menu in desktop mode
- [x] Add pointer icon (hand with pointing index finger) when hovering the theme selector button

2025-01-28 11:09 UTC, ivanslabbert commented on app/src/components/navigation/TopBar.vue
> +const isDarkMode = useDark();
Should this not perhaps be moved to globalConfig?

2025-02-09 05:18 UTC, ivanslabbert approved these changes

2025-02-12 03:21 UTC, merged