remove vee-validate from the cms
bccsa/luminary pull request #565
Opened 2024-11-29 11:38 UTC by belljohan3

vee-validate is only use in LInput. May be, we need to find a way to replace with something else ? @ivanslabbert

2024-12-02 07:17 UTC, ivanslabbert commented
> vee-validate is only use in LInput. May be, we need to find a way to replace with something else ? @ivanslabbert

I think vee-validate is a bit of an overkill for inline validation of one field. Check if it can be done manually in a simple way, so that we can remove the package and reduce weight.

2025-02-28 06:32 UTC, ivanslabbert requested changes
Looks good @belljohan3 but left one change request.

@DirkDevelopmentFreelance please do a functional check?

2025-02-28 06:32 UTC, ivanslabbert commented on cms/package.json
> +        "vue": "^3.3.11",
Why is the vue package being backdated from 3.5.13 to 3.3.11?

2025-02-28 11:41 UTC, belljohan3 commented on cms/package.json
> +        "vue": "^3.3.11",
It is probably a mistake from the rebase process

2025-03-04 06:24 UTC, DirkDevelopmentFreelance approved these changes
Seems good

2025-03-04 06:26 UTC, DirkDevelopmentFreelance requested changes

2025-03-04 06:26 UTC, DirkDevelopmentFreelance commented on cms/package.json
> +        "vue": "^3.3.11",
This still needs to be changed I think

2025-03-06 09:00 UTC, ivanslabbert requested changes

2025-03-06 16:55 UTC, closed without merging