517 api shared live api
bccsa/luminary pull request #590
Opened 2024-12-18 08:12 UTC by oslabbie

2025-01-06 12:05 UTC, ivanslabbert requested changes

2025-01-06 12:05 UTC, ivanslabbert commented on shared/src/socket/socketio.ts
> +            this.socket.emit("joinSocketGroups", { cms: this.isCms });
Change this to send the list of needed docs to the API to only send the needed documents to the client.

2025-01-06 12:05 UTC, ivanslabbert commented on shared/src/socket/socketio.ts
>      }
Remove function

2025-01-06 12:05 UTC, ivanslabbert commented on shared/src/types/dto.ts
> +export type apiConnectionOptions = {
```suggestion
export type ApiConnectionOptions = {
```

2025-01-06 13:09 UTC, oslabbie commented on shared/src/socket/socketio.ts
> +            this.socket.emit("joinSocketGroups", { cms: this.isCms });
This is already implemented with the isCms option 
We will have to re-impliment if we remove the isCms option

2025-01-06 13:26 UTC, oslabbie commented on api/src/docs/docs.service.ts
> +        );
This does not make sense to move into a separate class, since the implementation on the nest and socket side, is a specific implimentation, and not a universal implementation

2025-01-07 11:57 UTC, ivanslabbert approved these changes
Approved with comments

2025-01-07 12:21 UTC, merged